import { createBrowserRouter } from "react-router-dom";
import { Root } from "../../routes/Root";
import { ErrorPage } from "../../error-page";
import { NotReadyYetPage } from "../../not-ready-error-page";

const notReadyRoutes = [
  "/university",
  "/research",
  "/study",
  "/transfer",
  "/newsroom",
  "/events",
  "/maps",
  "/alumni",
  "/employees",
  "/doctoralCandidates",
  "/lecturers",
  "/press-media",
  "/friends-supporters",
  "/institutions",
  "/faculties",
  "/international",
  "/excellence-strategy",
  "/key-date-and-deadlines",
  "/course-overview",
  "/job-market",
  "/directions",
  "/university-portal",
  "/history",
  "/facts-and-figures",
  "/profiles",
  "/research-portal",
  "/research-profile",
  "/promoting-young-researchers",
  "/field-of-focus",
  "/study-portal",
  "/dergee-programmes",
  "/international-study",
  "/enroll",
  "/transfer-portal",
  "/reseach-city",
  "/technology-transfer",
  "/communication",
  "/contact-persons",
  "/people",
  "/university-institutions",
  "/rooms-buildings",
  "/course-catalogue",
  "/library-catalogue",
  "/phone-book",
  "/faculties",
  "/institutions",
  "/research-profiles",
  "/degree-programmes",
  "/facts-and-figures",
  "/deadlines-and-dates",
  "/helpline",
  "/events",
  "/saigon-nobel-prize-winners",
  "/saigon-global",
  "/saigon-nobel-prize-winners",
];

export const router = createBrowserRouter([
  {
    path: "/",
    element: <Root />,
    errorElement: <ErrorPage />,
  },
  ...notReadyRoutes.map((route) => ({
    path: route,
    element: <NotReadyYetPage />,
  })),
]);
